### ISSUE TITLE
Instruction Icons not shown.

### ISSUE THREAD

**Issue by habib-farhan** [wwwouaiebe/lrm-extensions#4]
Hi,
I am trying to get the route Itinerary when the gpxChanged event is fired by calling the function getRouteHTMLElement(options), everything is returned as it should except the instruction icons, just like on the demo page on the right menu, where theinstructions are there but the icons are not.
Why is that?
why doesnt it find the icon class, which is defined like this in code:
  	'IconClass' : 'leaflet-routing-icon-' + this._formatter.getIconName ( this._gpxRoute.instructions [ instrCounter ], instrCounter ) + '-big',

Any help is appreciated. 
Thanks in advance.

**Comment by wwwouaiebe** [comment]
IconClass is the CSS class used to display the icons.
I agree that the css file with the classes defintions is missing in the demo and in the Github repository. You can find this file attached to this message.
[lrm-extensions-icons.zip](https://github.com/wwwouaiebe/lrm-extensions/files/1880695/lrm-extensions-icons.zip)
